# config.yaml
coingecko:
  api_base: "https://api.coingecko.com/api/v3"
  api_key: null
  timeout: 20
  max_retries: 3
  initial_backoff: 1.0

openai:
  model: "gpt-4.1"
  fallback_model: "gpt-4o-mini"
  endpoint: "https://api.openai.com/v1"
  timeout: 60
  prompt_file: "prompts/summarize_sentiment.txt"
  max_tokens: 400
  max_tokens_cap: 2000
  auto_scale_max_tokens: true
  temperature: 0.0
  response_format: "json_object"

gemini:
  model: "gemini-2.5-flash"
  endpoint: "https://generativelanguage.googleapis.com/v1beta/models"
  timeout: 60
  prompt_file: "prompts/summarize_sentiment.txt"
  max_tokens: 400
  max_output_tokens_cap: 4096
  temperature: 0.0
  response_mime_type: "application/json"

xai:
  model: "grok-3-mini"
  endpoint: "https://api.x.ai/v1/chat/completions"
  timeout: 60
  prompt_file: "prompts/summarize_sentiment.txt"
  max_tokens: 1200
  max_tokens_cap: 4800
  auto_scale_max_tokens: true
  temperature: 0.0

gdelt:
  base_url: "https://api.gdeltproject.org/api/v2/doc/doc"
  timeout: 30
  max_retries: 3

google_news:
  hl: "en-US"
  gl: "US"
  ceid: "US:en"
  timeout: 15
  resolve_redirects: true
  max_workers: 4

news_query:
  major_assets_without_context: ["BTC", "ETH"]   # → Kontext wird für diese Assets weggelassen
  enforce_context_assets: ["SOL", "DOT", "XRP"]  # → Kontext bleibt für diese Assets aktiv

url_harvest:
  max_workers: 4

ensemble:
  use_openai: true
  use_gemini: true
  use_xai: true

news_domain_filter:
  enforce: true

database:
  default_path: "data/rrp.duckdb"

sentiment:
  domain_weight:
    mode: "hybrid"     # accepted_only | store_only | hybrid
    alpha: 0.6         # Mischung acc vs stored_total
    k: 3               # Laplace-Glättung für Normierung
    w_min: 0.7
    w_max: 1.3
  normalization:
    article_weight:
      enabled: true
      beta: 0.5        # sublinear
      cap: 3.0         # Max-Gewicht